apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-rag-secret-1-rhoai
  janus-idp.io/tekton: test-rag-secret-1-rhoai
  backstage.io/kubernetes-id: test-rag-secret-1-rhoai
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: test-rag-secret-1-rhoai
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
